# Generated by Django 4.2 on 2023-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_dish', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='ordering_dish.dish'),
        ),
        migrations.DeleteModel(
            name='DishOrder',
        ),
    ]
