# Generated by Django 4.2 on 2023-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_dish', '0003_order_dishes_delete_dishorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
